name: "gmod-upload"
description: "Packs a Garry's Mod addon to a .gma file and uploads to the Steam workshop"

branding:
  icon: box
  color: gray-dark

inputs:
  id:
    description: "Workshop item id"
    required: true
  changelog:
    description: "Changelog"
    required: false
    default: ""
  folder:
    description: "Path to folder containing addon files"
    required: false
    default: ${{ github.workspace }}
  dry-run:
    description: "If true, the action will only simulate the upload without actually performing it"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Cache SteamCMD
      id: cache-steamcmd
      uses: actions/cache@v4
      with:
          path: ~/Steam
          key: steamcmd-${{ runner.os }}

    - name: Download SteamCMD
      if: steps.cache-steamcmd.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install lib32gcc-s1
        mkdir ~/Steam
        curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf - -C ~/Steam

    - name: Create gma file
      shell: bash
      run: |
        wget -O /tmp/fastgmad.zip "https://github.com/WilliamVenner/fastgmad/releases/download/v0.2.0/fastgmad_linux.zip"
        unzip /tmp/fastgmad.zip -d /tmp/fastgmad
        chmod +x /tmp/fastgmad/fastgmad
        mkdir -p /tmp/addon
        /tmp/fastgmad/fastgmad create -folder . -out /tmp/addon/${{ inputs.id }}.gma
      working-directory: ${{ inputs.folder }}
    - name: Run gma packer
      shell: bash
      run: |
        lua ${{ github.action_path }}/gma.lua ${{ inputs.id }}.gma ${{ inputs.config }}

    - name: Create .vdf file
      shell: bash
      run: |
        cat > ${{ inputs.id }}.vdf << EOF
          "workshopitem" {
            "appid" "4000"
            "publishedfileid" "${{ inputs.id }}"
            "contentfolder" "/tmp/addon/${{ inputs.id }}.gma"
            "changenote" "${{ inputs.changelog }}"
          }
        EOF
      working-directory: /tmp/addon

    - name: Run SteamCMD
      shell: bash
      if: ${{ inputs.dry-run != 'true' }}
      run: |
        ~/Steam/steamcmd.sh +login $STEAM_USERNAME $STEAM_PASSWORD +workshop_build_item `pwd -P`/${{ inputs.id }}.vdf +quit
      working-directory: /tmp/addon

    - name: Print Errors
      if: failure()
      shell: bash
      run: |
        echo ~/Steam/logs/stderr.txt
        echo "$(cat ~/Steam/logs/stderr.txt)"
        echo
        echo ~/Steam/logs/workshop_log.txt
        echo "$(cat ~/Steam/logs/workshop_log.txt)"
        echo
        echo ~/Steam/workshopbuilds/depot_build_4000.log
        echo "$(cat ~/Steam/workshopbuilds/depot_build_4000.log)"

        exit 1
